Support multiple readers in the mapping-template component
cefriel/chimera pull request #21
Opened 2024-07-23 14:39 UTC by AuPath

Adds an endpoint to the mapping template component _"mapt://readers?..."_ that expects as input an exchange whose body contains a `Map<String,Reader>` of `Readers`.

If accepted, it should be merged only after https://github.com/cefriel/mapping-template/pull/27.

2024-07-26 14:19 UTC, marioscrock requested changes

2024-07-26 14:19 UTC, marioscrock commented on camel-chimera-mapping-template/src/main/java/com/cefriel/rdf/MaptTemplateProcessor.java
> +            TemplateExecutor templateExecutor;
Move TemplateExecutor as a field of the class MaptTemplateProducer to reuse the same instance across multiple executions of the same route

2024-09-25 19:34 UTC, marioscrock commented on camel-chimera-mapping-template/src/main/java/com/cefriel/rdf/MaptTemplateProcessor.java
> +        // which custom template functions to use ???
Move as an issue in the repo explaining current behaviour and changes to be discussed

2024-09-30 12:37 UTC, AuPath commented on camel-chimera-mapping-template/src/main/java/com/cefriel/rdf/MaptTemplateProcessor.java
> +                    if (reader != null) {
Changed so as to reflect changes to the mapping-template in https://github.com/cefriel/mapping-template/pull/30

2024-10-01 12:32 UTC, marioscrock requested changes

2024-10-01 12:32 UTC, marioscrock commented on camel-chimera-mapping-template/src/main/java/com/cefriel/rdf/MaptTemplateProcessor.java
> +                    if (reader != null) {
Here and in other invocations to the `mapping-template`, avoid repeated code blocks. Change as:

```java
Map<String, Reader> readers; //Check where defined and if we need to define it again
if (reader != null)
    readers = Map.of("reader", reader);
result = templateExecutor.executeMappingParametric(readers,
                                ResourceAccessor.open(params.template(), exchange),
                                ResourceAccessor.open(params.query(), exchange));
```

2024-10-01 12:32 UTC, marioscrock commented on camel-chimera-mapping-template/src/main/java/com/cefriel/rdf/MaptTemplateProcessor.java
> +                    if (reader != null) {
Ideally, define `readers` map at the beginning and then perform calls without checking `reader ` every time

2024-12-03 11:04 UTC, merged

2025-01-18 20:30 UTC, hamzabhatti5253 approved these changes